package morsecodelearner;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;





public class MainUI extends javax.swing.JFrame {


    

    public MainUI() {
        initComponents();
        setUpQuestionLabel();
        displayRandomCharacter();
        displaySkipAmount();
        displayRevAmount();
        displayAnswer();
        setTitle("Morse Code Learner");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
            private char currentChar;
            private int currentSkip;
            private int revAm;
            public void display() {
            setVisible(true);
            }
            
            private void displayRandomCharacter() {
            currentChar = MorseCodeConverter.getRandomCharacter();
            question.setText(String.valueOf(currentChar));

            }
            private void displaySkipAmount() {
            currentSkip = 0;
            skipAmount.setText(String.valueOf(currentSkip));
            }
            private void displayRevAmount() {
            revAm = 0;
            revAmount.setText(String.valueOf(revAm));
            }
            private void displayAnswer() {
                ansReveal.setText("");
            }
            private void setUpQuestionLabel() {
            submitAns.addActionListener((ActionEvent e) -> {

                String userAnswer = answer.getText().trim();
                
                

                String correctAnswer = MorseCodeConverter.toMorse(currentChar);
                

                if(userAnswer.equals(correctAnswer)) {
                    currentSkip = 0;
                    skipAmount.setText(String.valueOf(currentSkip));
                    JOptionPane.showMessageDialog(MainUI.this, "Correct!", "Feedback", JOptionPane.INFORMATION_MESSAGE);
                    displayRandomCharacter();
                } else if(userAnswer.equals("")){
                }else {
                    currentSkip++;
                    skipAmount.setText(String.valueOf(currentSkip));
                    JOptionPane.showMessageDialog(MainUI.this, "Incorrect. Try again.", "Feedback", JOptionPane.ERROR_MESSAGE);
                }
                answer.setText("");
                
            });
            revAns.addActionListener((ActionEvent e) -> {
                String morseCode = MorseCodeConverter.toMorse(currentChar);
                revAm++;
                revAmount.setText(String.valueOf(revAm));
                ansReveal.setText(morseCode);
            });
            skip.addActionListener((var e) -> {
                currentSkip++;
                skipAmount.setText(String.valueOf(currentSkip));
                ansReveal.setText("");
                displayRandomCharacter();
            });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        answer = new javax.swing.JTextPane();
        revAns = new javax.swing.JButton();
        question = new javax.swing.JLabel();
        submitAns = new javax.swing.JButton();
        skip = new javax.swing.JButton();
        skipAmount = new javax.swing.JLabel();
        revAmount = new javax.swing.JLabel();
        ansReveal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(answer);

        revAns.setText("Reveal");

        submitAns.setText("Submit");

        skip.setText("Skip");

        skipAmount.setText(null);

        revAmount.setText(null);

        ansReveal.setText(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(skipAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(revAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitAns, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(revAns, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ansReveal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(revAns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skip)
                .addGap(29, 29, 29)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ansReveal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitAns)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skipAmount)
                    .addComponent(revAmount))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ansReveal;
    private javax.swing.JTextPane answer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel question;
    private javax.swing.JLabel revAmount;
    private javax.swing.JButton revAns;
    private javax.swing.JButton skip;
    private javax.swing.JLabel skipAmount;
    private javax.swing.JButton submitAns;
    // End of variables declaration//GEN-END:variables



}
